# Credit Risk Decisioning System

End-to-end recruiter-grade workflow with four modeling tracks (LazyPredict, Manual Top-3, FLAML, PyCaret).

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from src.data_prep import load_home_credit_data, build_customer_level_table, temporal_leakage_checks, stratified_split
from src.features import build_preprocessor, prepare_model_inputs
from src.modeling import (
    run_lazypredict_discovery,
    select_top3_eligible_families,
    run_manual_engineering_track,
    run_flaml_track,
    run_pycaret_track,
    assign_decision_band,
    save_inference_bundle,
)
from src.evaluation import build_leaderboard, rerank_with_business_weights

SEED = 42
PROJECT_NAME = 'credit-risk-decisioning-system'
PROJECT_ROOT = Path('.')
RAW_DIR = PROJECT_ROOT / 'data' / 'raw' / 'home_credit'
ARTIFACT_DIR = PROJECT_ROOT / 'artifacts'
ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)

## 1) Business Problem and Success Criteria

Goal: reduce default risk while preserving approval volume.

Success criteria:
- Strong PR-AUC (class imbalance aware)
- Stable ROC-AUC and Brier calibration
- Actionable approve/review/reject policy
- Deployable scoring and monitoring hooks

## 2) Dataset Access and Data Dictionary

Dataset: Home Credit Default Risk (Kaggle).

Primary table:
- `application_train.csv`

Auxiliary tables used for aggregated customer signals:
- `bureau.csv`
- `previous_application.csv`
- `POS_CASH_balance.csv`
- `installments_payments.csv`
- `credit_card_balance.csv`

In [2]:
tables = load_home_credit_data(RAW_DIR, sample_frac=0.05, random_state=SEED)
{k: v.shape for k, v in tables.items()}

{'application_train': (15376, 122),
 'bureau': (72878, 17),
 'previous_application': (69999, 37),
 'POS_CASH_balance': (10001358, 8),
 'installments_payments': (13605401, 8),
 'credit_card_balance': (3840312, 23)}

## 3) Data Cleaning and Leakage Checks

- Build customer-level table from auxiliary aggregates
- Remove leak-prone or near-empty fields
- Validate target integrity before split

In [3]:
customer_df = build_customer_level_table(tables)
customer_df = temporal_leakage_checks(customer_df)
customer_df['TARGET'].value_counts(normalize=True)

TARGET
0    0.918444
1    0.081556
Name: proportion, dtype: float64

## 4) Feature Engineering

- Numeric aggregation features from auxiliary tables
- Categorical one-hot encoding
- Median/mode imputations and scaling for numeric stability

In [4]:
train_df, holdout_df = stratified_split(customer_df, target_col='TARGET', random_state=SEED)
preprocessor = build_preprocessor(train_df.drop(columns=['TARGET']))
X_train, X_holdout, y_train, y_holdout = prepare_model_inputs(
    train_df, holdout_df, target_col='TARGET', preprocessor=preprocessor
)
X_train.shape, X_holdout.shape

((12300, 371), (3076, 371))

## 5) Validation Strategy

- Stratified train/holdout split
- Track-specific CV where applicable (manual, FLAML, PyCaret)
- Primary metric: PR-AUC
- Secondary metric: ROC-AUC
- Tertiary metric: Brier score

In [5]:
summary = pd.DataFrame({
    'split': ['train', 'holdout'],
    'rows': [len(train_df), len(holdout_df)],
    'target_rate': [train_df['TARGET'].mean(), holdout_df['TARGET'].mean()]
})
summary

     split   rows  target_rate
0    train  12300     0.081545
1  holdout   3076     0.081599

## 6) Track 1: LazyPredict Discovery Lab

LazyPredict runs on the post-preprocessing matrix to identify promising model families quickly.

In [6]:
lazy_table = run_lazypredict_discovery(X_train, X_holdout, y_train, y_holdout)
lazy_table.head(15)

,Model,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Time Taken
0,CatBoostClassifier,0.9200,0.502283,0.743815,0.882443,5.400215
1,LinearDiscriminantAnalysis,0.9120,0.541304,0.726220,0.889607,0.243510
2,RidgeClassifier,0.9196,0.499783,0.720967,0.881467,0.086818
3,RidgeClassifierCV,0.9196,0.499783,0.719707,0.881467,0.225804
4,CalibratedClassifierCV,0.9200,0.500000,0.706965,0.881667,89.504110
5,XGBClassifier,0.9172,0.516739,0.704722,0.885874,1.110887
6,LinearSVC,0.9164,0.502609,0.702141,0.881335,4.576482
7,LGBMClassifier,0.9184,0.505978,0.701304,0.883104,0.483222
8,LogisticRegression,0.9160,0.529783,0.695922,0.888841,0.246563
9,AdaBoostClassifier,0.9160,0.527500,0.682803,0.888259,3.450731
10,SVC,0.9200,0.500000,0.681616,0.881667,4.931723
11,RandomForestClassifier,0.9200,0.500000,0.664080,0.881667,3.243653
12,ExtraTreesClassifier,0.9200,0.500000,0.662495,0.881667,1.071218
13,BernoulliNB,0.7368,0.608152,0.648785,0.791814,0.110078
14,BaggingClassifier,0.9192,0.517826,0.615785,0.887009,8.597522

## 7) Selection of Top 3 Eligible Models

Eligibility filters applied:
- stability (Brier not extreme)
- speed and practicality
- interpretability fit for risk use-case

Only eligible top 3 families move into manual engineering.

In [7]:
eligible_table, top3_families = select_top3_eligible_families(
    lazy_table, X_train, y_train, X_holdout, y_holdout, random_state=SEED
)
eligible_table, top3_families

/home/ahmad/AI/Projects/credit-risk-decisioning-system/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

(                   lazy_model               family    pr_auc   roc_auc  \
 0          CatBoostClassifier             catboost  0.262586  0.752329
 1               XGBClassifier              xgboost  0.226912  0.752236
 2  LinearDiscriminantAnalysis  logistic_regression  0.221028  0.729195

       brier  train_time_sec interpretability  eligible eligibility_note
 0  0.068493        8.561943       medium-low      True         eligible
 1  0.071213       69.346832       medium-low      True         eligible
 2  0.197666       11.593717             high      True         eligible  ,
 ['catboost', 'logistic_regression', 'xgboost'])

## 8) Track 2: Manual Engineering Lab

For each selected family:
- explicit training code
- calibration where relevant
- threshold optimization
- decision-band assignment

In [8]:
manual_results, manual_models = run_manual_engineering_track(
    top3_families=top3_families,
    X_train=X_train, y_train=y_train,
    X_holdout=X_holdout, y_holdout=y_holdout,
    random_state=SEED,
)
manual_results[['model_name', 'pr_auc', 'roc_auc', 'brier', 'optimized_threshold', 'policy_utility']]

/home/ahmad/AI/Projects/credit-risk-decisioning-system/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

,model_name,pr_auc,roc_auc,brier,optimized_threshold,policy_utility
0,catboost,0.271494,0.762344,0.068580,0.11,-615.0
1,xgboost,0.240332,0.762309,0.070456,0.10,-611.0
2,logistic_regression,0.221028,0.729195,0.197666,0.63,-849.0

In [9]:
best_manual_idx = manual_results['pr_auc'].idxmax()
best_manual_row = manual_results.loc[best_manual_idx]
bands = assign_decision_band(
    best_manual_row['holdout_scores'],
    approve_threshold=0.25,
    reject_threshold=0.65,
)
pd.Series(bands).value_counts(normalize=True).rename('share')

approve          0.970741
manual_review    0.028609
reject           0.000650
Name: share, dtype: float64

## 9) Track 3: FLAML Optimization Lab

FLAML is run with explicit budget and PR-AUC objective to search for budget-aware challengers.

In [10]:
flaml_result = run_flaml_track(
    X_train=X_train,
    y_train=y_train,
    X_holdout=X_holdout,
    y_holdout=y_holdout,
    time_budget=240,
    random_state=SEED,
)
flaml_result

[flaml.automl.logger: 06-11 18:29:23] {2375} INFO - task = classification

[flaml.automl.logger: 06-11 18:29:23] {2386} INFO - Evaluation method: cv

[flaml.automl.logger: 06-11 18:29:23] {2489} INFO - Minimizing error metric: 1-ap

[flaml.automl.logger: 06-11 18:29:23] {2606} INFO - List of ML learners in AutoML Run: ['lgbm', 'xgboost', 'rf', 'extra_tree', 'lrl1']

[flaml.automl.logger: 06-11 18:29:23] {2911} INFO - iteration 0, current learner lgbm

[flaml.automl.logger: 06-11 18:29:28] {3046} INFO - Estimated sufficient time budget=45617s. Estimated necessary time budget=760s.

[flaml.automl.logger: 06-11 18:29:28] {3097} INFO -  at 4.6s,	estimator lgbm's best error=8.3187e-01,	best estimator lgbm's best error=8.3187e-01

[flaml.automl.logger: 06-11 18:29:28] {2911} INFO - iteration 1, current learner lgbm

[flaml.automl.logger: 06-11 18:29:33] {3097} INFO -  at 9.6s,	estimator lgbm's best error=8.3187e-01,	best estimator lgbm's best error=8.3187e-01

[flaml.automl.logger: 06-11 18:29:33] {2911} INFO - iteration 2, current learner lgbm

[flaml.automl.logger: 06-11 18:29:44] {3097} INFO -  at 20.2s,	estimator lgbm's best error=8.1382e-01,	best estimator lgbm's best error=8.1382e-01

[flaml.automl.logger: 06-11 18:29:44] {2911} INFO - iteration 3, current learner xgboost

[flaml.automl.logger: 06-11 18:29:47] {3097} INFO -  at 24.1s,	estimator xgboost's best error=8.4216e-01,	best estimator lgbm's best error=8.1382e-01

[flaml.automl.logger: 06-11 18:29:47] {2911} INFO - iteration 4, current learner lgbm

[flaml.automl.logger: 06-11 18:30:02] {3097} INFO -  at 38.2s,	estimator lgbm's best error=8.0431e-01,	best estimator lgbm's best error=8.0431e-01

[flaml.automl.logger: 06-11 18:30:02] {2911} INFO - iteration 5, current learner xgboost

[flaml.automl.logger: 06-11 18:30:04] {3097} INFO -  at 40.6s,	estimator xgboost's best error=8.4164e-01,	best estimator lgbm's best error=8.0431e-01

[flaml.automl.logger: 06-11 18:30:04] {2911} INFO - iteration 6, current learner extra_tree

[flaml.automl.logger: 06-11 18:30:04] {3097} INFO -  at 40.8s,	estimator extra_tree's best error=8.6878e-01,	best estimator lgbm's best error=8.0431e-01

[flaml.automl.logger: 06-11 18:30:04] {2911} INFO - iteration 7, current learner extra_tree

[flaml.automl.logger: 06-11 18:30:04] {3097} INFO -  at 40.9s,	estimator extra_tree's best error=8.5873e-01,	best estimator lgbm's best error=8.0431e-01

[flaml.automl.logger: 06-11 18:30:04] {2911} INFO - iteration 8, current learner lgbm

[flaml.automl.logger: 06-11 18:30:10] {3097} INFO -  at 46.3s,	estimator lgbm's best error=8.0431e-01,	best estimator lgbm's best error=8.0431e-01

[flaml.automl.logger: 06-11 18:30:10] {2911} INFO - iteration 9, current learner extra_tree

[flaml.automl.logger: 06-11 18:30:10] {3097} INFO -  at 46.4s,	estimator extra_tree's best error=8.4710e-01,	best estimator lgbm's best error=8.0431e-01

[flaml.automl.logger: 06-11 18:30:10] {2911} INFO - iteration 10, current learner extra_tree

[flaml.automl.logger: 06-11 18:30:10] {3097} INFO -  at 46.6s,	estimator extra_tree's best error=8.4710e-01,	best estimator lgbm's best error=8.0431e-01

[flaml.automl.logger: 06-11 18:30:10] {2911} INFO - iteration 11, current learner extra_tree

[flaml.automl.logger: 06-11 18:30:10] {3097} INFO -  at 46.7s,	estimator extra_tree's best error=8.4710e-01,	best estimator lgbm's best error=8.0431e-01

[flaml.automl.logger: 06-11 18:30:10] {2911} INFO - iteration 12, current learner extra_tree

[flaml.automl.logger: 06-11 18:30:10] {3097} INFO -  at 47.0s,	estimator extra_tree's best error=8.3157e-01,	best estimator lgbm's best error=8.0431e-01

[flaml.automl.logger: 06-11 18:30:10] {2911} INFO - iteration 13, current learner extra_tree

[flaml.automl.logger: 06-11 18:30:10] {3097} INFO -  at 47.1s,	estimator extra_tree's best error=8.3157e-01,	best estimator lgbm's best error=8.0431e-01

[flaml.automl.logger: 06-11 18:30:10] {2911} INFO - iteration 14, current learner extra_tree

[flaml.automl.logger: 06-11 18:30:11] {3097} INFO -  at 47.2s,	estimator extra_tree's best error=8.3157e-01,	best estimator lgbm's best error=8.0431e-01

[flaml.automl.logger: 06-11 18:30:11] {2911} INFO - iteration 15, current learner extra_tree

[flaml.automl.logger: 06-11 18:30:11] {3097} INFO -  at 47.6s,	estimator extra_tree's best error=8.0520e-01,	best estimator lgbm's best error=8.0431e-01

[flaml.automl.logger: 06-11 18:30:11] {2911} INFO - iteration 16, current learner extra_tree

[flaml.automl.logger: 06-11 18:30:11] {3097} INFO -  at 48.0s,	estimator extra_tree's best error=8.0327e-01,	best estimator extra_tree's best error=8.0327e-01

[flaml.automl.logger: 06-11 18:30:11] {2911} INFO - iteration 17, current learner lgbm

[flaml.automl.logger: 06-11 18:30:26] {3097} INFO -  at 62.7s,	estimator lgbm's best error=7.8903e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:26] {2911} INFO - iteration 18, current learner extra_tree

[flaml.automl.logger: 06-11 18:30:27] {3097} INFO -  at 63.2s,	estimator extra_tree's best error=8.0327e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:27] {2911} INFO - iteration 19, current learner rf

[flaml.automl.logger: 06-11 18:30:27] {3097} INFO -  at 63.4s,	estimator rf's best error=8.8101e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:27] {2911} INFO - iteration 20, current learner rf

[flaml.automl.logger: 06-11 18:30:27] {3097} INFO -  at 63.8s,	estimator rf's best error=8.7172e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:27] {2911} INFO - iteration 21, current learner rf

[flaml.automl.logger: 06-11 18:30:28] {3097} INFO -  at 64.2s,	estimator rf's best error=8.5262e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:28] {2911} INFO - iteration 22, current learner rf

[flaml.automl.logger: 06-11 18:30:28] {3097} INFO -  at 64.5s,	estimator rf's best error=8.4363e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:28] {2911} INFO - iteration 23, current learner rf

[flaml.automl.logger: 06-11 18:30:28] {3097} INFO -  at 64.7s,	estimator rf's best error=8.4363e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:28] {2911} INFO - iteration 24, current learner extra_tree

[flaml.automl.logger: 06-11 18:30:29] {3097} INFO -  at 65.1s,	estimator extra_tree's best error=7.9776e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:29] {2911} INFO - iteration 25, current learner extra_tree

[flaml.automl.logger: 06-11 18:30:29] {3097} INFO -  at 65.5s,	estimator extra_tree's best error=7.9776e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:29] {2911} INFO - iteration 26, current learner rf

[flaml.automl.logger: 06-11 18:30:29] {3097} INFO -  at 65.9s,	estimator rf's best error=8.3314e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:29] {2911} INFO - iteration 27, current learner extra_tree

[flaml.automl.logger: 06-11 18:30:30] {3097} INFO -  at 66.4s,	estimator extra_tree's best error=7.9240e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:30] {2911} INFO - iteration 28, current learner extra_tree

[flaml.automl.logger: 06-11 18:30:30] {3097} INFO -  at 66.8s,	estimator extra_tree's best error=7.9240e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:30] {2911} INFO - iteration 29, current learner extra_tree

[flaml.automl.logger: 06-11 18:30:31] {3097} INFO -  at 67.5s,	estimator extra_tree's best error=7.9240e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:31] {2911} INFO - iteration 30, current learner rf

[flaml.automl.logger: 06-11 18:30:31] {3097} INFO -  at 67.7s,	estimator rf's best error=8.3314e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:31] {2911} INFO - iteration 31, current learner lgbm

[flaml.automl.logger: 06-11 18:30:55] {3097} INFO -  at 91.7s,	estimator lgbm's best error=7.8903e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:55] {2911} INFO - iteration 32, current learner rf

[flaml.automl.logger: 06-11 18:30:55] {3097} INFO -  at 91.9s,	estimator rf's best error=8.3314e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:55] {2911} INFO - iteration 33, current learner extra_tree

[flaml.automl.logger: 06-11 18:30:56] {3097} INFO -  at 92.3s,	estimator extra_tree's best error=7.9240e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:56] {2911} INFO - iteration 34, current learner rf

[flaml.automl.logger: 06-11 18:30:56] {3097} INFO -  at 92.9s,	estimator rf's best error=8.0746e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:56] {2911} INFO - iteration 35, current learner rf

[flaml.automl.logger: 06-11 18:30:57] {3097} INFO -  at 93.8s,	estimator rf's best error=8.0746e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:57] {2911} INFO - iteration 36, current learner extra_tree

[flaml.automl.logger: 06-11 18:30:58] {3097} INFO -  at 94.3s,	estimator extra_tree's best error=7.9240e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:58] {2911} INFO - iteration 37, current learner rf

[flaml.automl.logger: 06-11 18:30:58] {3097} INFO -  at 94.7s,	estimator rf's best error=8.0746e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:58] {2911} INFO - iteration 38, current learner extra_tree

[flaml.automl.logger: 06-11 18:30:59] {3097} INFO -  at 95.7s,	estimator extra_tree's best error=7.9240e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:30:59] {2911} INFO - iteration 39, current learner rf

[flaml.automl.logger: 06-11 18:31:00] {3097} INFO -  at 96.5s,	estimator rf's best error=8.0543e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:31:00] {2911} INFO - iteration 40, current learner extra_tree

[flaml.automl.logger: 06-11 18:31:01] {3097} INFO -  at 97.1s,	estimator extra_tree's best error=7.9240e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:31:01] {2911} INFO - iteration 41, current learner extra_tree

[flaml.automl.logger: 06-11 18:31:02] {3097} INFO -  at 98.8s,	estimator extra_tree's best error=7.9240e-01,	best estimator lgbm's best error=7.8903e-01

[flaml.automl.logger: 06-11 18:31:02] {2911} INFO - iteration 42, current learner lgbm

[flaml.automl.logger: 06-11 18:31:15] {3097} INFO -  at 111.5s,	estimator lgbm's best error=7.8663e-01,	best estimator lgbm's best error=7.8663e-01

[flaml.automl.logger: 06-11 18:31:15] {2911} INFO - iteration 43, current learner extra_tree

[flaml.automl.logger: 06-11 18:31:16] {3097} INFO -  at 112.4s,	estimator extra_tree's best error=7.9240e-01,	best estimator lgbm's best error=7.8663e-01

[flaml.automl.logger: 06-11 18:31:16] {2911} INFO - iteration 44, current learner extra_tree

[flaml.automl.logger: 06-11 18:31:16] {3097} INFO -  at 112.7s,	estimator extra_tree's best error=7.9240e-01,	best estimator lgbm's best error=7.8663e-01

[flaml.automl.logger: 06-11 18:31:16] {2911} INFO - iteration 45, current learner extra_tree

[flaml.automl.logger: 06-11 18:31:16] {3097} INFO -  at 113.1s,	estimator extra_tree's best error=7.9240e-01,	best estimator lgbm's best error=7.8663e-01

[flaml.automl.logger: 06-11 18:31:16] {2911} INFO - iteration 46, current learner rf

[flaml.automl.logger: 06-11 18:31:17] {3097} INFO -  at 113.5s,	estimator rf's best error=8.0543e-01,	best estimator lgbm's best error=7.8663e-01

[flaml.automl.logger: 06-11 18:31:17] {2911} INFO - iteration 47, current learner extra_tree

[flaml.automl.logger: 06-11 18:31:18] {3097} INFO -  at 114.3s,	estimator extra_tree's best error=7.9240e-01,	best estimator lgbm's best error=7.8663e-01

[flaml.automl.logger: 06-11 18:31:18] {2911} INFO - iteration 48, current learner lgbm

[flaml.automl.logger: 06-11 18:31:23] {3097} INFO -  at 119.5s,	estimator lgbm's best error=7.8002e-01,	best estimator lgbm's best error=7.8002e-01

[flaml.automl.logger: 06-11 18:31:23] {2911} INFO - iteration 49, current learner lgbm

[flaml.automl.logger: 06-11 18:31:37] {3097} INFO -  at 133.1s,	estimator lgbm's best error=7.8002e-01,	best estimator lgbm's best error=7.8002e-01

[flaml.automl.logger: 06-11 18:31:37] {2911} INFO - iteration 50, current learner extra_tree

[flaml.automl.logger: 06-11 18:31:37] {3097} INFO -  at 133.4s,	estimator extra_tree's best error=7.9240e-01,	best estimator lgbm's best error=7.8002e-01

[flaml.automl.logger: 06-11 18:31:37] {2911} INFO - iteration 51, current learner lgbm

[flaml.automl.logger: 06-11 18:32:09] {3097} INFO -  at 165.5s,	estimator lgbm's best error=7.8002e-01,	best estimator lgbm's best error=7.8002e-01

[flaml.automl.logger: 06-11 18:32:09] {2911} INFO - iteration 52, current learner lgbm

[flaml.automl.logger: 06-11 18:32:16] {3097} INFO -  at 172.7s,	estimator lgbm's best error=7.8002e-01,	best estimator lgbm's best error=7.8002e-01

[flaml.automl.logger: 06-11 18:32:16] {2911} INFO - iteration 53, current learner lgbm

[flaml.automl.logger: 06-11 18:32:34] {3097} INFO -  at 190.7s,	estimator lgbm's best error=7.8002e-01,	best estimator lgbm's best error=7.8002e-01

[flaml.automl.logger: 06-11 18:32:34] {2911} INFO - iteration 54, current learner lgbm

[flaml.automl.logger: 06-11 18:33:02] {3097} INFO -  at 218.2s,	estimator lgbm's best error=7.8002e-01,	best estimator lgbm's best error=7.8002e-01

[flaml.automl.logger: 06-11 18:33:02] {2911} INFO - iteration 55, current learner extra_tree

[flaml.automl.logger: 06-11 18:33:03] {3097} INFO -  at 219.3s,	estimator extra_tree's best error=7.9240e-01,	best estimator lgbm's best error=7.8002e-01

[flaml.automl.logger: 06-11 18:33:03] {2911} INFO - iteration 56, current learner xgboost

[flaml.automl.logger: 06-11 18:33:06] {3097} INFO -  at 222.5s,	estimator xgboost's best error=8.2553e-01,	best estimator lgbm's best error=7.8002e-01

[flaml.automl.logger: 06-11 18:33:06] {2911} INFO - iteration 57, current learner xgboost

[flaml.automl.logger: 06-11 18:33:09] {3097} INFO -  at 225.3s,	estimator xgboost's best error=8.2553e-01,	best estimator lgbm's best error=7.8002e-01

[flaml.automl.logger: 06-11 18:33:09] {2911} INFO - iteration 58, current learner xgboost

[flaml.automl.logger: 06-11 18:33:14] {3097} INFO -  at 230.8s,	estimator xgboost's best error=8.0996e-01,	best estimator lgbm's best error=7.8002e-01

[flaml.automl.logger: 06-11 18:33:14] {2911} INFO - iteration 59, current learner lgbm

[flaml.automl.logger: 06-11 18:33:20] {3097} INFO -  at 237.0s,	estimator lgbm's best error=7.8002e-01,	best estimator lgbm's best error=7.8002e-01

[flaml.automl.logger: 06-11 18:33:20] {2911} INFO - iteration 60, current learner extra_tree

[flaml.automl.logger: 06-11 18:33:21] {3097} INFO -  at 237.4s,	estimator extra_tree's best error=7.9240e-01,	best estimator lgbm's best error=7.8002e-01

[flaml.automl.logger: 06-11 18:33:21] {2911} INFO - iteration 61, current learner rf

[flaml.automl.logger: 06-11 18:33:22] {3097} INFO -  at 238.2s,	estimator rf's best error=8.0543e-01,	best estimator lgbm's best error=7.8002e-01

[flaml.automl.logger: 06-11 18:33:22] {2911} INFO - iteration 62, current learner extra_tree

[flaml.automl.logger: 06-11 18:33:23] {3097} INFO -  at 239.2s,	estimator extra_tree's best error=7.9240e-01,	best estimator lgbm's best error=7.8002e-01

[flaml.automl.logger: 06-11 18:33:23] {2911} INFO - iteration 63, current learner extra_tree

[flaml.automl.logger: 06-11 18:33:24] {3097} INFO -  at 240.3s,	estimator extra_tree's best error=7.9240e-01,	best estimator lgbm's best error=7.8002e-01

[flaml.automl.logger: 06-11 18:33:27] {3359} INFO - retrain lgbm for 3.3s

[flaml.automl.logger: 06-11 18:33:27] {3362} INFO - retrained model: LGBMClassifier(colsample_bytree=0.8913821757158379,
               learning_rate=0.19961122310826113, max_bin=31,
               min_child_samples=13, n_estimators=41, n_jobs=-1, num_leaves=5,
               reg_alpha=0.17967797142195352, reg_lambda=0.030313868202178677,
               verbose=-1)

[flaml.automl.logger: 06-11 18:33:27] {2636} INFO - fit succeeded

[flaml.automl.logger: 06-11 18:33:27] {2637} INFO - Time taken to find the best model: 119.48342084884644

{'model_name': 'lgbm',
 'library_source': 'flaml',
 'pr_auc': 0.24883879538861708,
 'roc_auc': 0.7512364700490076,
 'brier': 0.0686443159859727,
 'train_time_sec': 243.57422753600986,
 'infer_latency_ms': 3.0018923660585037,
 'p95_latency_ms': 6.029514454712626,
 'calibration_metric': 0.0686443159859727,
 'best_config': {'n_estimators': 41,
  'num_leaves': 5,
  'min_child_samples': 13,
  'learning_rate': 0.19961122310826113,
  'log_max_bin': 5,
  'colsample_bytree': 0.8913821757158379,
  'reg_alpha': 0.17967797142195352,
  'reg_lambda': 0.030313868202178677},
 'best_loss': 0.7800174557835158,
 'time_budget': 240,
 'interpretability_note': 'FLAML challenger under explicit budget'}

## 10) Track 4: PyCaret Experiment Lab

PyCaret orchestration for compare/tune/calibrate/finalize workflow and deployability check.

In [11]:
pycaret_result = run_pycaret_track(
    train_df=train_df,
    holdout_df=holdout_df,
    target_col='TARGET',
    session_id=SEED,
    model_output_path=ARTIFACT_DIR / 'pycaret_credit_risk',
)
pycaret_result

{'model_name': 'pycaret_failed',
 'library_source': 'pycaret',
 'pr_auc': nan,
 'roc_auc': nan,
 'brier': nan,
 'train_time_sec': nan,
 'infer_latency_ms': nan,
 'p95_latency_ms': nan,
 'calibration_metric': nan,
 'interpretability_note': "PyCaret unavailable or failed: ('Pycaret only supports python 3.9, 3.10, 3.11. Your actual Python version: ', sys.version_info(major=3, minor=12, micro=10, releaselevel='final', serial=0), 'Please DOWNGRADE your Python version.')",
 'status': 'failed'}

## 11) Unified Leaderboard and Final Model Ranking

Includes LazyPredict top candidates, manual top 3, FLAML winner, PyCaret finalized model, and business baseline.

In [12]:
baseline_rows = [{
    'model_name': 'rule_based_income_ratio_baseline',
    'primary': 0.0,
    'secondary': 0.0,
    'tertiary': 0.25,
    'note': 'Business reference only; replace after scorecard benchmark run'
}]

leaderboard = build_leaderboard(
    project_name=PROJECT_NAME,
    task_type='binary_classification',
    lazy_results=eligible_table,
    manual_results=manual_results,
    flaml_result=flaml_result,
    pycaret_result=pycaret_result,
    baseline_rows=baseline_rows,
    manual_model_objects=manual_models,
)
leaderboard = rerank_with_business_weights(leaderboard)
leaderboard.head(10)

,project_name,task_type,library_source,model_name,cv_metric_mean,cv_metric_std,holdout_primary_metric,holdout_secondary_metric,holdout_tertiary_metric,calibration_metric,train_time_sec,infer_latency_ms,p95_latency_ms,model_size_mb,retrain_time_sec,interpretability_note,rank_score,final_rank
0,credit-risk-decisioning-system,binary_classification,manual,catboost,NaN,NaN,0.271494,0.762344,0.068580,0.068580,27.838844,2.998693,3.778982,4.447565,27.838844,Manual catboost with explicit thresholds and c...,0.341777,1
1,credit-risk-decisioning-system,binary_classification,lazypredict,catboost,NaN,NaN,0.262586,0.752329,0.068493,0.068493,8.561943,NaN,NaN,NaN,NaN,eligible,0.332494,2
2,credit-risk-decisioning-system,binary_classification,flaml,lgbm,NaN,NaN,0.248839,0.751236,0.068644,0.068644,243.574228,3.001892,6.029514,NaN,243.574228,FLAML challenger under explicit budget,0.322514,3
3,credit-risk-decisioning-system,binary_classification,lazypredict,xgboost,NaN,NaN,0.226912,0.752236,0.071213,0.071213,69.346832,NaN,NaN,NaN,NaN,eligible,0.310795,4
4,credit-risk-decisioning-system,binary_classification,manual,logistic_regression,NaN,NaN,0.221028,0.729195,0.197666,0.197666,13.817003,0.073335,0.099667,0.003676,13.817003,Manual logistic_regression with explicit thres...,0.295021,5
5,credit-risk-decisioning-system,binary_classification,lazypredict,logistic_regression,NaN,NaN,0.221028,0.729195,0.197666,0.197666,11.593717,NaN,NaN,NaN,NaN,eligible,0.288858,6
6,credit-risk-decisioning-system,binary_classification,manual,xgboost,NaN,NaN,0.240332,0.762309,0.070456,0.070456,192.840122,27.408260,38.979984,4.268757,192.840122,Manual xgboost with explicit thresholds and ca...,0.277731,7
7,credit-risk-decisioning-system,binary_classification,baseline,rule_based_income_ratio_baseline,NaN,NaN,0.000000,0.000000,0.250000,NaN,NaN,NaN,NaN,NaN,NaN,Business reference only; replace after scoreca...,-0.031291,8
8,credit-risk-decisioning-system,binary_classification,pycaret,pycaret_failed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PyCaret unavailable or failed: ('Pycaret only ...,-0.031291,9

In [13]:
leaderboard.to_csv(ARTIFACT_DIR / 'leaderboard_credit_risk.csv', index=False)
leaderboard[['model_name', 'library_source', 'rank_score', 'final_rank']].head(10)

                         model_name library_source  rank_score  final_rank
0                          catboost         manual    0.341777           1
1                          catboost    lazypredict    0.332494           2
2                              lgbm          flaml    0.322514           3
3                           xgboost    lazypredict    0.310795           4
4               logistic_regression         manual    0.295021           5
5               logistic_regression    lazypredict    0.288858           6
6                           xgboost         manual    0.277731           7
7  rule_based_income_ratio_baseline       baseline   -0.031291           8
8                    pycaret_failed        pycaret   -0.031291           9

## 12) Business Recommendation

Document in this section after execution:
- Why rank-1 is preferred for production
- When rank-2 may be safer (stability/latency/interpretability)
- Which tradeoff prevented another strong model from winning

## 13) Inference / Deployment Path

Persist chosen model + preprocessor + thresholds for FastAPI scoring.

In [14]:
winner = leaderboard.sort_values('final_rank').iloc[0]['model_name']
if winner in manual_models:
    save_inference_bundle(
        model=manual_models[winner],
        preprocessor=preprocessor,
        output_dir=ARTIFACT_DIR,
        approve_threshold=0.25,
        reject_threshold=0.65,
    )
    print(f'Saved manual winner: {winner}')
else:
    print('Winner not in manual track; save selected production artifact separately.')

Saved manual winner: catboost

## 14) Monitoring / Drift / Retraining Plan

Recommended production checks:
- PR-AUC, ROC-AUC, Brier on rolling windows
- band distribution drift (approve/review/reject)
- score PSI and feature drift
- manual-review override rate
- retraining SLA and champion/challenger cadence

## 15) Limitations and Next Steps

- Add external bureau updates for recency-aware features
- Stress test fairness and reject-inference strategy
- Add explainability slices by segment and approval band
- Run seed stability reruns for top 3 finalists